### ISSUE TITLE
Issue with node 10 and 11

### ISSUE THREAD

**Issue by stephanfriedrich** [tomusdrw/grunt-sync#60]
hi, 
thx for your plugin.

i got an error with the current node version 10 and 11 and grunt-sync within Linux Mint.
with node version 8.9 LTS everything works fine.

node: **v11.9.0** v10.15.1
npm: **6.5.0**
grunt-cli: **v1.3.2**
grunt: **v1.0.3**

My project and config is ok. looks like a bug in grunt-sync

```
Loading "sync.js" tasks...ERROR
>> TypeError: Cannot read property 'length' of undefined
>>     at exports.convertNodeAsyncFunction (/home/big-lebowski/project-carpet/src/html/node_modules/grunt-sync/node_modules/promised-io/promise.js:633:28)
>>     at Object.<anonymous> (/home/big-lebowski/project-carpet/src/html/node_modules/grunt-sync/node_modules/promised-io/fs.js:27:16)
>>     at Module._compile (internal/modules/cjs/loader.js:734:30)
>>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
>>     at Module.load (/home/big-lebowski/project-carpet/src/html/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
>>     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
>>     at Module.require (internal/modules/cjs/loader.js:663:17)
>>     at require (internal/modules/cjs/helpers.js:20:18)
>>     at Object.<anonymous> (/home/big-lebowski/project-carpet/src/html/node_modules/grunt-sync/tasks/sync.js:1:72)
>>     at Module._compile (internal/modules/cjs/loader.js:734:30)
>>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
>>     at Module.load (/home/big-lebowski/project-carpet/src/html/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
>>     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
>>     at Module.require (internal/modules/cjs/loader.js:663:17)
>>     at require (internal/modules/cjs/helpers.js:20:18)
>>     at loadTask (/home/big-lebowski/project-carpet/src/html/node_modules/grunt/lib/grunt/task.js:313:10)
>>     at /home/big-lebowski/project-carpet/src/html/node_modules/grunt/lib/grunt/task.js:351:7
>>     at Array.forEach (<anonymous>:null:null)
>>     at loadTasks (/home/big-lebowski/project-carpet/src/html/node_modules/grunt/lib/grunt/task.js:350:11)
>>     at Task.task.loadNpmTasks (/home/big-lebowski/project-carpet/src/html/node_modules/grunt/lib/grunt/task.js:398:5)
>>     at Object.module.exports (/home/big-lebowski/project-carpet/src/html/gruntfile.js:768:9)
>>     at loadTask (/home/big-lebowski/project-carpet/src/html/node_modules/grunt/lib/grunt/task.js:315:10)
>>     at Task.task.init (/home/big-lebowski/project-carpet/src/html/node_modules/grunt/lib/grunt/task.js:434:5)
>>     at Object.grunt.tasks (/home/big-lebowski/project-carpet/src/html/node_modules/grunt/lib/grunt.js:111:8)
>>     at Liftoff.<anonymous> (/opt/node/lib/node_modules/grunt-cli/bin/grunt:66:13)
>>     at Liftoff.execute (/opt/node/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:203:12)
>>     at module.exports (/opt/node/lib/node_modules/grunt-cli/node_modules/flagged-respawn/index.js:51:3)
>>     at Liftoff.<anonymous> (/opt/node/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:195:5)
>>     at Liftoff.<anonymous> (/opt/node/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:170:7)
>>     at processTicksAndRejections (internal/process/next_tick.js:74:9)
Warning: Task "sync:webfonts" not found. Use --force to continue.
```

**Comment by gitDylanHub** [comment]
What version of sync are you running?

**Comment by gitDylanHub** [comment]
Looks like I am running grunt-sync@0.2.4.  Would a newer version of sync resolve this issue?  And is it backwards compatible?

**Comment by yassineim** [comment]
Updating to 0.8.0 did resolve the issue for me. No idea about backwards compatibility though.

**Comment by gitDylanHub** [comment]
Updating to 0.8.0 resolved my issue as well. If it follows semantic versioning it is only a minor update, there should be no breaking changes and backwards compatible.

**Comment by staabm** [comment]
yep, fixed with https://github.com/tomusdrw/grunt-sync/releases/tag/v0.8.0

**Comment by tomusdrw** [comment]
Closing then.
